//********** HTML СТРАНИЦЫ (ГЛОБАЛЬНЫЕ ПЕРЕМЕННЫЕ)**********//


//Текстовые строки для WEB интерфейса.
//Весь HTML код обёрнут в модификатор переменной PROGMEM для хранения кода во Flash.

String webPage;   // Переменная для фармирования страниц из кусков ниже и вывода готового результата в браузер

//Шапка для всех страниц
const char webHeader_HTML[] PROGMEM = R"=====(<!DOCTYPE html><html><head><meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta name="viewport" content="width = device-width"><title>Wake-On-Line(ESP-01)</title>)=====";
String webHeader = (String)webHeader_HTML;


//Вернуться на предыдущую страницу, через 1 сек.
const char webBackPage_HTML[] PROGMEM = R"=====(<meta http-equiv="refresh"content="1;URL=/">)=====";
String webBackPage = (String)webBackPage_HTML;


//Страница сброса настроек WiFi
const char webResetSettings_HTML[] PROGMEM = R"=====(</head><body onmousedown="return false;" onclick="return true;"><p style="color:#ff0000"><strong>Произведён сброс настроек WiFi!</strong></p><p>Подключитесь к WiFi сети: <br><font color="#ff0000">"Wake-On-Line"</font> со смартфона<br>(пароль: 123456789).<br><font color="#0000FF">Введите SSID</font> и <font color="#0000FF">pswd</font> вашей<br>точки доступа в WiFiManager.<br><br>А так же <font color="#0000FF">Логин</font> и <font color="#0000FF">Пароль</font> для<br>Авторизации на WEB морде.<br>ГОТОВО!<br><br>Можно узнавать IP адрес ESP-01<br>и подключаться к WEB морде.</p></body></html>)=====";
String webResetSettings = (String)webResetSettings_HTML;


//Страница со словом "Загрузка..."
const char webLoading_HTML[] PROGMEM = R"=====(</head><body onmousedown="return false;" onclick="return true;"><br><br><br><br><br><h1>&nbsp;&nbsp;&nbsp;Загрузка...</h1></body></html>)=====";
String webLoading = (String)webLoading_HTML;


//Главные страницы управления через WEB
const char webControl_on_HTML[] PROGMEM = R"=====(<style>.buttonOFF{display: inline-block;cursor: not-allowed; position: absolute; top: 258px; left: 157px; font-size:20px;text-decoration:none;padding:21px 12px; color:#c0c0c0;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonON{display: inline-block;cursor: pointer; position: absolute; top: 258px; left: 235px; font-size:20px;text-decoration:none;padding:21px 5px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonON:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonReset{display: inline-block;cursor: pointer; position: absolute; top: 60px; left: 25px; font-size:14px;text-decoration:none;padding:12px 30px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonReset:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonSettings{display: inline-block;cursor: pointer; position: absolute; top: 60px; left: 162px; font-size:14px;text-decoration:none;padding:12px 30px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonSettings:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonRefresh{display: inline-block;cursor: pointer; position: absolute; top: 343px; left: 20px; font-size:19px;text-decoration:none;padding:14px 30px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonRefresh:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;}</style><script>function proverka() {if (confirm("Точно желаешь ЖЁСТКО выключить PC?")) {return true;} else {return false;}}</script></head><body onmousedown="return false;" onclick="return true;"><h1>Управление PC</h1><br><br><a class="buttonReset" onclick="return proverka()" href="/hard">Reset</a><a class="buttonSettings" href="/settings">Настройки</a><table style="text-align: left; height: 222px; width: 312px;" border="1" cellspacing="2" cellpadding="2"><tbody><tr><td style="font-size: 17pt; text-align: center; width: 80px;">Состояние PC</td><td style="font-size: 20pt; text-align: center; background-color: green; width: 135px;">ON</td></tr><tr><td style="font-size: 20pt; text-align: center; width: 60px;">Система</td><td style="text-align: center; width: 140px;"><a class="buttonOFF">Вкл.</a><a class="buttonON" href="/off">Выкл.</a></td></tr></tbody></table><a class="buttonRefresh" onClick="window.location.reload()">Обновить состояние PC</a><br><br><br><br>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<a href="/authorization?DISCONNECT=YES">Выйти из системы!</a></body></html>)=====";
String webControl_on = (String)webControl_on_HTML;

const char webControl_off_HTML[] PROGMEM = R"=====(<style>.buttonOFF{display: inline-block;cursor: not-allowed; position: absolute; top: 258px; left: 235px; font-size:20px;text-decoration:none;padding:21px 5px; color:#c0c0c0;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonON{display: inline-block;cursor: pointer; position: absolute; top: 258px; left: 157px; font-size:20px;text-decoration:none;padding:21px 12px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonON:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonReset{display: inline-block;cursor: pointer; position: absolute; top: 60px; left: 25px; font-size:14px;text-decoration:none;padding:12px 30px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonReset:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonSettings{display: inline-block;cursor: pointer; position: absolute; top: 60px; left: 162px; font-size:14px;text-decoration:none;padding:12px 30px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonSettings:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonRefresh{display: inline-block;cursor: pointer; position: absolute; top: 343px; left: 20px; font-size:19px;text-decoration:none;padding:14px 30px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonRefresh:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;}</style><script>function proverka() {if (confirm("Точно желаешь ЖЁСТКО выключить PC?")) {return true;} else {return false;}}</script></head><body onmousedown="return false;" onclick="return true;"><h1>Управление PC</h1><br><br><a class="buttonReset" onclick="return proverka()" href="/hard">Reset</a><a class="buttonSettings" href="/settings">Настройки</a><table style="text-align: left; height: 222px; width: 312px;" border="1" cellspacing="2" cellpadding="2"><tbody><tr><td style="font-size: 17pt; text-align: center; width: 80px;">Состояние PC</td><td style="font-size: 20pt; text-align: center; background-color: red; width: 135px;">OFF</td></tr><tr><td style="font-size: 20pt; text-align: center; width: 60px;">Система</td><td style="text-align: center; width: 140px;"><a class="buttonOFF">Выкл.</a><a class="buttonON" href="/on">Вкл.</a></td></tr></tbody></table><a class="buttonRefresh" onClick="window.location.reload()">Обновить состояние PC</a><br><br><br><br>&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;&ensp;<a href="/authorization?DISCONNECT=YES">Выйти из системы!</a></body></html>)=====";
String webControl_off = (String)webControl_off_HTML;


//Страница с настройками
const char webSettings_HTML[] PROGMEM = R"=====(<body><style>.buttonBack{display: inline-block;cursor: pointer; position: absolute; top: 60px; left: 25px; font-size:14px;text-decoration:none;padding:12px 25px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonBack:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonInfo{display: inline-block;cursor: pointer; position: absolute; top: 60px; left: 162px; font-size:14px;text-decoration:none;padding:11px 11px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonInfo:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonWebLoginPasswd{display: inline-block;cursor: pointer; position: absolute; top: 120px; left: 25px; font-size:14px;text-decoration:none;padding:14px 28px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonWebLoginPasswd:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonFirmware{display: inline-block;cursor: pointer; position: absolute; top: 185px; left: 25px; font-size:14px;text-decoration:none;padding:14px 40px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonFirmware:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonReboot{display: inline-block;cursor: pointer; position: absolute; top: 250px; left: 25px; font-size:14px;text-decoration:none;padding:14px 50px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonReboot:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;} .buttonResWiFi{display: inline-block;cursor: pointer; position: absolute; top: 315px; left: 25px; font-size:14px;text-decoration:none;padding:14px 50px; color:#394d5c;background:#d5dce0;border-radius:10px;border:5px solid #354251;} .buttonResWiFi:hover{background:#354251;color:#ffffff;border:5px solid #354251;transition: all 0.5s ease;}</style><script>function proverka() {if (confirm("Точно желаешь сбросить WiFi пароль?")) {return true;} else {return false;}}</script></head><body onmousedown="return false;" onclick="return true;"><h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Настройки</h1><br><br><a class="buttonBack" onclick="history.back()">&laquo; Назад</a><a class="buttonInfo" href="/ipInform">&#9992; Информация</a><a class="buttonWebLoginPasswd" href="/webPasswd">&#8277; Настройки WEB авторизации</a><a class="buttonFirmware" href="/firmware">&#8648; Обновить прошивку ESP</a><a class="buttonReboot" href="/rebootESP-01">&#8634; Перезагрузить ESP-01</a><a class="buttonResWiFi" onclick="return proverka()" href="/resetEraseESP">&#10554; Сбросить пароль WiFi</a></body></html>)=====";
String webSettings = (String)webSettings_HTML;


//Страница с информацией
const char webInfo1_HTML[] PROGMEM = R"=====(</head><body><h1>&nbsp;Информация</h1><a href="/"><button>&ltrie; На главную</button></a>&emsp;&emsp;<button onClick="window.location.reload();">Обновить</button><br><br>)=====";
String webInfo1 = (String)webInfo1_HTML;


//Страница настроек авторизации на WEB интерфейсе
const char webLoginPasswd_HTML[] PROGMEM = R"=====(</head><body><h1>&nbsp;WEB настройки</h1><form method="POST" action="saveDataEEPROM"><input value="&laquo; Назад" type="submit" onclick="history.back()">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input value="Применить &#10004;" type="submit"><p style="color:#ff0000"><strong>Введите новые данные</strong></p><label style="color:#0000FF">Логин:&nbsp;&nbsp;&nbsp;</label><input name="login" placeholder="Введите Логин" required><br><br><label style="color:#0000FF">Пароль:&nbsp;</label><input name="pswd" type="password" placeholder="Введите Пароль" required></form></body></html>)=====";
String webLoginPasswd = (String)webLoginPasswd_HTML;


//Страница с ошибкой 404 (Page Not Found!)
const char webPageNotFound_HTML[] PROGMEM = R"=====(<body><h1 style="color:#0000FF">Page Not Found!</h1><p><strong>Иди в ОЧКО с моей страницы!</strong></p><h3 style="color:#ff0000">&emsp;&emsp;&emsp;ПИДРИЛА!</h3></body></html></body></html>)=====";
String webPageNotFound = (String)webPageNotFound_HTML;
